language: ruby
sudo: false
cache: bundler
bundler_args: --without yard guard benchmarks tools
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
    - CODECLIMATE_REPO_TOKEN=86bb9d558da8217d85126a02c4a264dc8789bb4cc8d3949e8fcbabca0440f2fa
install:
  - "wget -nc http://download.geteventstore.com/binaries/EventStore-OSS-Linux-v3.0.3.tar.gz"
  - "tar -xvzf EventStore-OSS-Linux-v3.0.3.tar.gz"
  - "mv EventStore-OSS-Linux-v3.0.3 .event_store"
  - "cd .event_store && ./run-node.sh --db ./ESData &"
  - "bundle install"
script: "bundle exec rake ci"
rvm:
  - 2.0
  - 2.1
  - rbx-2
  - jruby
  - jruby-head
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
